[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
todo_list_app = "CYVmbKB1b1tUTxvCoVU5w4id8bBUt5SsEByaUDytAcvn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
